//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyFonts
{
    
    internal partial class ViewResources
    {
        private static System.Resources.ResourceManager manager;
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((ViewResources.manager == null))
                {
                    ViewResources.manager = new System.Resources.ResourceManager("TinyFonts.ViewResources", typeof(ViewResources).Assembly);
                }
                return ViewResources.manager;
            }
        }
        internal static Microsoft.SPOT.Font GetFont(ViewResources.FontResources id)
        {
            return ((Microsoft.SPOT.Font)(Microsoft.SPOT.ResourceUtility.GetObject(ResourceManager, id)));
        }
        [System.SerializableAttribute()]
        internal enum FontResources : short
        {
            Small = -19474,
        }
    }
}
